import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import Landing from "@components/Landing";
import Main from "@components/Main";
import withTransition from "@components/withTransition";
import { useLuksoWeb3 } from "@components/LuksoWeb3Provider";

const Home: NextPage = () => {
  const { address } = useLuksoWeb3();

  return (
    <div className={styles.container}>
      <Head>
        <title>Marble: LUKSO-Native Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!address ? <Landing /> : <Main />}
        {!address && (
          <>
            {/* i like colorful floating marbles, do you? */}
            <Box className={styles.marbleOne}></Box>
            <Box className={styles.marbleTwo}></Box>
          </>
        )}
      </main>
    </div>
  );
};

export default withTransition(Home);
