import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import useIssuedTokens from "../hooks/useIssuedTokens";
import styles from "../styles/Home.module.css";
import { Image } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { address } = useAccount();
  const { tokens: issuedTokens, isLoading } = useIssuedTokens(address);

  console.log("tokens: ", issuedTokens);
  console.log("isLoading: ", isLoading);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <ConnectButton />
        {isLoading ? (
          <div>Loading...</div>
        ) : (
          issuedTokens.map(
            ({
              name,
              symbol,
              iconUrl,
              metadata,
              totalSupply,
              creationType,
            }) => {
              return (
                <>
                  <div>{name}</div>
                  <div>{symbol}</div>
                  <Image src={iconUrl} alt="image" />
                </>
              );
            }
          )
        )}
      </main>
    </div>
  );
};

export default Home;
